discord:
  token: ${DISCORD_TOKEN}

spring:
  flyway:
    enabled: true
  datasource:
    url: jdbc:h2:file:./data/discord_dota
    username: sa
    password: password
    driverClassName: org.h2.Driver
